# Statistics and Mathematics in Data Science

**Prepared by:** Timothy Jonah E. Borromeo<br>
<b><u><i>Introduction to Data Science</b></u></i><br><br>

## Vital Role of Statistics and Mathematics in Data Science

Data Science is a multifaceted discipline, encompassing aspects of statistics, computer science, and domain knowledge. Statistics and Mathematics serve as the foundational pillars of Data Science, providing a rigorous framework for making sense of data, ensuring that insights are derived systematically and accurately. <br>

They enable data scientists to quantify uncertainty and variability through `probabilty theory` and `statistical ineference`, allowing for rigorus `hypothesis testing` and robust model building. Mathematical principles such as `calculus` and `linear algebra` are essential for developing `optimization` algorithms and understanding the inner workings of `machine learning` models. Moreover, `descriptive` and `inferential statistics` facilitate data summarization, visualization, and the reduction of complex, high-dimensional data into more manageable forms.

## What types of <i>math</i> do Data Scientists need to know?

Data Scientists utilize mathematics to:
- Understand and use Machine Learning algorithms
- Analyze datasets from various sources
- Identify patterns in data
- Forecast trends and growth

> Data Scientists utilizes mathematical fucnctions to perform <u>data analysis</u> and apply <u>machine learning</u> like clustering, regression, and classification.

<!-- Data Scientists use three main types of maths — <b><u>Linear Algebra, Calculus, and Statistics</u></b> -->
## Key Concepts

### Core Statistical Foundations
- **Descriptive Statistics**
  * Descriptive statistics summarize and describe the main features of a dataset. They provide a "snapshot" of the data’s distribution, central tendency, and variability.
    - > **Measures of Central Tendency:**<br>
        Mean: Average value. Sensitive to outliers.<br>
        Median: Middle value when data is ordered. Robust to outliers.<br>
        Mode: Most frequent value. Useful for categorical data
      
- **Inferential Statistics**
  * Inferential statistics generalize conclusions from a sample to a population, quantifying uncertainty through probability.
    - > Central Limit Theorem (CLT)<br>
      > Confidence Intervals<br>
      > Hypothesis Testing
- **Regression Analysis**
  * Regression models relationships between a dependent variable (y) and one or more independent variables (X).
    - > *Linear Regression*<br>
      > *Logistic Regression*<br>
      > *Regularization*
- **Bayesian Statistics**
  * Bayesian statistics updates beliefs (probabilities) as new evidence is observed, using Bayes’ theorem.
    - > *Prior Distribution*: Initial belief about a parameter (e.g., "30% of emails are spam").<br>
*Likelihood*: Probability of observing the data given the parameter (
P
(
data
∣
θ
)
P(data∣θ)).<br>
*Posterior Distribution*: Updated belief after observing data (
P
(
θ
∣
data
)
P(θ∣data))<br>
*Markov Chain Monte Carlo (MCMC)*: Computational method to approximate complex posteriors.
- **Time Series Analysis**
  * Time series analysis models data points collected sequentially over time.
    - > *Trend*: Long-term upward/downward movement (e.g., rising global temperatures).<br>
        *Seasonality*: Regular patterns (e.g., holiday sales spikes).<br>
        *Stationarity*: Mean and variance constant over time (required for ARIMA models).<br>
        *Autocorrelation*: Correlation of a series with its lagged values.

### Core Mathematical Foundations
- **Probabilty**
  * Probabilty quantifies uncertainty by modeling the likelihood of events or outcomes. It provides the language to describe randomness of data.
    - > Distributions (normal, binomial, Poisson), Bayes’ theorem, random variables, expectation, variance, covariance. 
- **Linear Algebra**
  * Linear algebra deals with vectors, matrices, and linear transformations. It underpins how data is structured and manipulated computationally.
    - > Vectors, matrices, eigenvalues, eigenvectors, matrix factorization (SVD, PCA).
- **Calculus**
  * Calculus studies rates of change (derivatives) and accumulation (integrals). It is essential for optimizing models and understanding how variables interact.
    - >  Derivatives, integrals, gradients, optimization (e.g., gradient descent).
- **Discrete Mathematics**
  * Discrete math deals with countable, non-continuous structures. It is foundational for algorithm design and combinatorial analysis.
    - > Graph theory, combinatorics, logic.

# Machine Learning Fundamentals

Machine Learning lies at the core of AI, enabling systems to learn from given data and improving predictive and classification perfomances over time. By building a strong foundation in mathematics and statistics, you can gain a deeper understanding of data science and machine learning.

## How they work together

Mathematics provides the language and tools for representing and manipulating data, while statistics provides the methods for analyzing and interpreting that data. In machine learning, these two areas are combined to build models that can learn from data and make predictions.

# Lets Try!
__Lets do Descriptive Statistics__

<b><i>Descriptive statistics</b></i> (sometimes called <b><i>summary statistics</b></i>) are quantitative values we can calculate to summarize information about our dataset. Calculating these statistics is typically the first step when performing exploratory data analysis (EDA).

For this example, we'll look at a classic introductory machine learning dataset, the [`Titanic Dataset`](https://www.kaggle.com/c/titanic).

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

import matplotlib
matplotlib.use('TkAgg')  # or 'Qt5Agg'

In [3]:
dataset = sns.load_dataset('titanic')
dataset.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

Most of the column headers (we'll call them features or predictors from now on) are self-explanatory. Click [`here`](https://www.kaggle.com/c/titanic/data) to find a more thorough description of the data.

As a final note, the values that we'll be calculating below are actually called <b><i>sample statistics</b></i> (e.g. sample mean, sample variance, etc.). From a frequentist perspective, they are merely <b><u>estimates</b></u> of the true parameters, which are fixed but unknown.

### Min and Max  

<b><i>Min</b></i> and <b><i>Max</b></i> refer to the minimum and maximum data values of a particular feature. Note that this does not refer to the <i>theoretical</i> min and max values that the feature can take.

In [4]:
# To get an initial look on the statistical details of the dataset
dataset.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [5]:
# To check the quality of the dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

#### Q1.

Calculate the min and max values for `age`.

In [7]:
min(dataset['age'])

0.42

In [6]:
max(dataset['age'])

80.0

#### Q2.

Calculate the min and max values for `fare`.

In [8]:
min(dataset['fare'])

0.0

In [9]:
max(dataset['fare'])

512.3292

In [10]:
dataset['fare'].min()  # Pandas method: returns the minimum value in the 'fare' column

0.0

In [11]:
dataset['fare'].max()

512.3292

## Quantiles and Percentiles

Now for some formal discussion.

Let $X$ be a r.v. with cdf $F$.

For each $p \in \left[0, 1\right]$, define $F^{-1}(p)$ to be the smallest value $x$ such that $F(x) \geq p$. 

Then $F^{-1}(p)$ is called the $p$ <b><i>quantile</b></i> of $X$ or the $100p$ <b><i>percentile</b></i> of $X$.

The function $F^{-1}$ is called the <b><i>quantile function</b></i> of $X$.

Quantiles are used as cut points that divide a probability distribution into intervals of equal probability. For example, the <b><i>quartiles</b></i> of a distribution are defined by three points that split the distribution into four equally-sized groups. These points are the 25th, 50th, and 75th percentile.

* In simple terms:
    - Percentiles/quantiles = cut points in your data
    - They help you understand how data is distributed
    - They answer questions like:
>> “What value separates the lowest 25% from the rest?”

#### Q3.

Calculate the 80th, 90th, and 99th percentile of `fare`. Ignore NaN values.

In [12]:
dataset['fare'].quantile(q=0.8)

39.6875

In [13]:
dataset['fare'].quantile(q=0.9)

77.9583

In [14]:
dataset['fare'].quantile(q=0.99)

249.00622000000035

#### Q4.

Calculate the first, second, and third quartiles for `age`. Print this.

Create a density plot for `age` and overlay the quartiles by plotting red vertical lines. Note that density plots $\neq$ histograms.

Ignore NaN values.

In [15]:
print(dataset['age'].quantile(q=0.25))
print(dataset['age'].quantile(q=0.50))
print(dataset['age'].quantile(q=0.75))

quart = dataset[['age']].dropna().quantile([0.25, 0.5, 0.75])

20.125
28.0
38.0

## Measures of Central Tendency

### Mean

The <b><i>sample mean</b></i> $\bar{x}$ of a feature $X$ with data points $x_1, x_2, \ldots, x_n$ is defined as

$$\bar{x} = \frac{1}{n}\sum_{i=1}^{n}x_i$$

#### Q5.

Calculate the sample mean of `age`. Ignore NaN values.

In [16]:
np.mean(dataset['age'])

29.69911764705882

### Median

The <b><i>median</b></i> is defined as the 50th percentile. It is the value that divides the data into two equal groups.

More formally, every number $m$ with the following property is called the median of a r.v. $X$:

$$P(X \leq m) \geq 0.5 \quad \text{ and } \quad P(X \geq m) \geq 0.5$$

Note that there can be more than one median.

#### Q6.

Calculate the median of `age`. Ignore NaN values.

In [17]:
np.median(dataset['age'].dropna())

28.0

### Mode

The <b><i>mode</b></i> is defined as the most frequent value. It corresponds to the maxima of a distribution. 

Distributions with just one maxima are called <b><i>unimodal</b></i>, while those with multiple maximas are called <b><i>multi-modal</b></i> (e.g. a distribution with two modes is called <b><i>bimodal</b></i>).

For continuous distributions (subject to certain assumptions), we can find the modes by finding the maximum of a pdf $f$, i.e. solving

$$\frac{d}{dx}f(x) = 0$$

#### Q7.

Calculate the mode of `age`. Ignore NaN values.

In [18]:
dataset['age'].dropna().mode()

0    24.0
Name: age, dtype: float64

## Measures of Spread / Dispersion

### Variance / Standard Deviation

The (unbiased) <b><i>sample variance</b></i> $s^2$ of a feature $X$ with data points $x_1, x_2, \ldots, x_n$ is defined as

$$s^2 = \frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2$$

The <b><i>sample standard deviation</b></i> $s$ is the non-negative square root of the sample variance.

#### Q8.

Calculate the <b><u>unbiased</b></u> sample variance and sample standard deviation of `age`. Ignore NaN values.

<i>Hint</i>: If you are using a numpy function, you might want to double check your answer. Try reading the API.

In [19]:
np.var(dataset['age'])

210.7235797536662

In [21]:
# Variance and Standard Deviation of Age (Using the formula)
age_series = dataset['age'].dropna()
age_mean = sum(age_series)/len(age_series)
vars2 = (sum((age_series - age_mean)**2))*(1/(len(age_series)-1))
print('The unbiased sample variance is', '%.3f' % vars2)

std1 = np.sqrt(vars2)
print('The unbiased sample standard deviation is', '%.3f' % std1)

The unbiased sample variance is 211.019
The unbiased sample standard deviation is 14.526

In [22]:
# Variance and Standard Deviation of Age (Using numpy and pandas)
var = np.var(dataset['age'].dropna())
print("The Variance is", '%.3f' % var)

std = dataset['age'].dropna().std()
print("The Standard Deviation is", '%.3f' % std)

The Variance is 210.724
The Standard Deviation is 14.526

### Range

The <b><i>range</b></i> of your data is defined as difference between the maximum and minimum values. It gives you an idea about the span or width your data values.

#### Q9.

Calculate the range of `age`. Ignore NaN values.

In [23]:
max(dataset['age']) - min(dataset['age'])

79.58

#### Interquartile Range (IQR)

The <b><i>interquartile range</b></i> (IQR) defined as the difference between the 75th and 25th percentile. It is typically used when creating box plots, and is also used as a proxy for variance when expectations do not exist (e.g. Cauchy distribution).

#### Q10.

Calculate the IQR of `age`. Ignore NaN values.

In [24]:
stats.iqr(dataset['age'].dropna())

17.875

***Simple Interpretaion for this is that:***<br>
<u>*Half of the passengers have ages within a range of about 18 years*</u>

So why not full range?<br>
Because:
* Min and max can be affected by outliers
* IQR focuses only on the central bulk of the data

## Higher Moments

Beyond centrality and spread, there are two higher moment statistics used to describe the shape of a distribution.

### Skewness

The <b><i>skewness</b></i> of a distribution measures the degree of asymmetry of a distribution around the mean. Its value can be positive, zero, negative, or undefined.

For unimodal distributions, negative skew means that the tail of the distribution is on the left side, while a positive skew indicates that the tail is on the right. For example, if we apply the exponential function on a r.v. $X$ with Normal distribution (which has zero skew since it is symmetric), we create a new r.v. $Y = \exp(X)$ which has a [`log-normal distribution`](https://en.wikipedia.org/wiki/Log-normal_distribution) and is positively skewed.

Formally, the skewness of a r.v. $X$ is defined as

$$\tilde{\mu}_3 = E\left[\left(\frac{X - \mu}{\sigma}\right)^3\right]$$

The <b><i>sample skewness</b></i> is

$$\frac{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^3}{s^3}$$

#### Q11.

Calculate the sample skewness of `age`. Ignore NaN values.

In [25]:
stats.skew(dataset['age'].dropna())

0.3882898514698657

### Kurtosis

The <b><i>kurtosis</b></i> of a distribution measures its "tailedness" (i.e. how heavy the tails are). In essence, a higher kurtosis indicates a greater probability of outliers occurring. A description of the types of kurtosis (<b><i>Mesokurtic</b></i>, <b><i>Leptokurtic</b></i>, and <b><i>Platykurtic</b></i>) can be read [`here`](https://en.wikipedia.org/wiki/Kurtosis#Excess_kurtosis).

Formally, the kurtosis of a r.v. $X$ is defined as

$$\tilde{\mu}_4 = E\left[\left(\frac{X - \mu}{\sigma}\right)^4\right]$$

The <b><i>sample kurtosis</b></i> is

$$\frac{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^4}{\left[\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2\right]^2} - 3$$

#### Q12.

Calculate the sample kurtosis of `age`. Ignore NaN values.

In [26]:
stats.kurtosis(dataset['age'].dropna())

0.16863657224286044

# References

[Mathematics and Data Science: Its Role and Relevance - pickl.ai](https://www.pickl.ai/blog/mathematics-and-data-science-its-role-and-relevance/)<br>
[The Vital Role of Statistics and Mathematics in Data Science and AI Engineering](https://www.linkedin.com/pulse/vital-role-statistics-mathematics-data-science-ai-abdul-qadir-4swzc/)<br>
[How much math is involved in Data Science?](https://www.multiverse.io/en-GB/blog/how-much-math-data-science)<br>
[Introduction to Mathematics and Statistics for Data Science and machine learning - medium.com](https://medium.com/@avikumart_/introduction-to-mathematics-and-statistics-for-data-science-and-machine-learning-2560403baf31)